# https://taskfile.dev

version: '3'

tasks:
  build:
    vars:
      PACKAGE: '{{default "suia" .PACKAGE}}'
    dir: ./move_packages/{{ .PACKAGE}}
    cmds:
      - sui move build --skip-fetch-latest-git-deps
    sources:
      - ./**/*.move
      - Move.toml
  test:
    vars:
      PACKAGE: '{{default "suia" .PACKAGE}}'
    dir: ./move_packages/{{ .PACKAGE}}
    cmds:
      - sui move test --skip-fetch-latest-git-deps
    sources:
      - sources/**/*.move
      - Move.toml
  demo-suia:
    deps:
      - task: build
        vars: {PACKAGE: "suia"}
    cmds:
      - yarn ts-node demo/demo.ts
    sources:
      - ./**/*.move
      - ./**/Move.toml
      - demo/demo.ts
      - .env
  demo-capy:
    deps:
      - task: build
    cmds:
      - yarn ts-node demo/suia_capy.ts
    sources:
      - demo/suia_capy.ts
      - .env
