# https://taskfile.dev

version: '3'

tasks:
  build:
    vars:
      PACKAGE: '{{default "suia" .PACKAGE}}'
    dir: ./packages/{{ .PACKAGE}}
    cmds:
      - sui move build --skip-fetch-latest-git-deps
    sources:
      - sources/**/*.move
      - Move.toml
  test:
    vars:
      PACKAGE: '{{default "suia" .PACKAGE}}'
    dir: ./packages/{{ .PACKAGE}}
    cmds:
      - sui move test --skip-fetch-latest-git-deps
    sources:
      - sources/**/*.move
      - Move.toml
  demo-one:
    vars:
      PACKAGE: '{{default "suia" .DEMO}}'
    deps:
      - build
    cmds:
      - yarn ts-node demo/{{ .DEMO}}.ts
    sources:
      - demo/{{ .DEMO}}.ts
      - .env
  demo-all:
    cmds:
      - task demo-one DEMO=suia -f
      - task demo-one DEMO=suia_capy -f
      - task demo-one DEMO=showcase -f
    sources:
      - demo/*.ts
      - .env
